version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout

      - run:
          name: test
          command: |
            make test
      - run:
          command: pip install coveralls

      - run:
          name: gen-coverage
          command: |
            make coverage
            coveralls
      - run:
          name: upload-coverage
          command: |
            bash <(curl -s https://codecov.io/bash)

workflows:
  main:
    jobs:
      - build-and-test
